---
title: "In class exercise 3"
author: "Toh Jun Long"
date: "8/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
packages = c('sf', 'tmap', 'tidyverse')
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
```

```{r}
mpsz = st_read(dsn = "Hands-on_Ex03/data/geospatial",
               layer = "MP14_SUBZONE_WEB_PL")
mpsz
```

```{r}
colSums(is.na(mpsz))
```

```{r}
popdata = read_csv("Hands-on_Ex03/data/aspatial/respopagesextod2011to2020.csv")
popdata
```

```{r}
popdatatest =  popdata %>% 
  filter(Time == 2020) %>% 
  group_by(PA,SZ,AG) %>% 
  summarise(`POP` = sum(`Pop`)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = AG,
              values_from = POP)
```


```{r}

popdata2020 = popdata %>% 
  filter(Time == 2020) %>% 
  group_by(PA,SZ,AG) %>% 
  summarise(`POP` = sum(`Pop`)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = AG,
              values_from = POP) %>% 
  mutate(YOUNG = rowSums(.[3:6])
         + rowSums(.[12])) %>% 
mutate(`ECONOMY ACTIVE` = rowSums(.[7:11]) +
         rowSums(.[13:15])) %>% 
mutate(`AGED` = rowSums(.[16:21])) %>% 
mutate(`TOTAL` = rowSums(.[3:21])) %>% 
mutate(`DEPENDENCY` = (`YOUNG` + `AGED`)/`ECONOMY ACTIVE`) %>% 
  select(`PA`,`SZ`,`YOUNG`,`ECONOMY ACTIVE`, `AGED`, `TOTAL`,`DEPENDENCY`)
popdata2020

```

```{r}
popdata2020 = popdata2020 %>% 
  mutate_at(.vars = vars(PA,SZ),
            .funs = funs(toupper)) %>% 
  filter(`ECONOMY ACTIVE`> 0)
```
```{r}
mpsz_pop2020 = left_join(mpsz, popdata2020,
                         by = c('SUBZONE_N' = "SZ"))
```

```{r}
tmap_mode("plot")
qtm(mpsz_pop2020,
    fill = "DEPENDENCY")
```

```{r}
tm_shape(mpsz_pop2020)+
  tm_fill("DEPENDENCY",
          style = "quantile",
          palette = "Blues",
          title = "Dependency ratio")+
  tm_layout(main.title = "Distribution of Dependencey Ratio by planning subszone",
            main.title.position = "center",
            main.title.size = 1.2,
            legend.width = 0.35,
            legend.height = 0.45,
            frame = TRUE) #+
  tm_borders(alpha = 0.5) +
  tm_compass(type = "8star",size = 2)+
  tm_scale_bar()+
  tm_grid(alpha = 0.2)+
  tm_credits("Source: Planning Sub-zone boundary from Urban Redevelopment Authorithy (URA)\n and Population data from Department of Statistics DOS",
             position = c("left","bottom"))
```

```{r}
tm_shape(mpsz_pop2020)+
  tm_polygons()
```

```{r}
tm_shape(mpsz_pop2020)+
  tm_polygons("DEPENDENCY")
```

```{r}
tm_shape(mpsz_pop2020)+
  tm_fill("DEPENDENCY")
```

```{r}
tm_shape(mpsz_pop2020)+
  tm_fill("DEPENDENCY")+
  tm_borders(lwd=0.1,alpha=0.1)
```
```{r}
tm_shape(mpsz_pop2020)+
  tm_fill("DEPENDENCY",
          n=5,
          style = "jenks")+
  tm_borders(alpha=0.5)
```
```{r}
tm_shape(mpsz_pop2020)+
  tm_fill("DEPENDENCY",
          n=5,
          style = "equal")+
  tm_borders(alpha=0.5)
```
```{r}
tm_shape(mpsz_pop2020)+
  tm_fill("DEPENDENCY",
          n=5,
          style = "quantile")+
  tm_borders(alpha=0.5)
```
```{r}
tm_shape(mpsz_pop2020)+
  tm_fill("DEPENDENCY",
          n=5,
          style = "sd")+
  tm_borders(alpha=0.5)
```
```{r}
tm_shape(mpsz_pop2020)+
  tm_fill("DEPENDENCY",
          n=5,
          style = "kmeans")+
  tm_borders(alpha=0.5)
```

```{r}
summary(mpsz_pop2020$DEPENDENCY)
```
```{r}
tm_shape(mpsz_pop2020)+
  tm_fill("DEPENDENCY",
          breaks = c(0,0.60,0.70,0.80,0.90,1.00))+
  tm_borders(alpha = 0.5)
```
```{r}
tm_shape(mpsz_pop2020)+
  tm_fill("DEPENDENCY",
          n=6,
          style= "quantile",
          palette = "Blues")+
  tm_borders(alpha = 0.5)
```
```{r}
tm_shape(mpsz_pop2020)+
  tm_fill("DEPENDENCY",
          n=6,
          style= "quantile",
          palette = "-Greens")+
  tm_borders(alpha = 0.5)
```
```{r}
tm_shape(mpsz_pop2020)+
  tm_fill("DEPENDENCY",
          style = "jenks",
          palette = "Blues",
          legend.hist = TRUE,
          legend.is.portrait = TRUE,
          legend.hist.z = 0.1)+
  tm_layout(main.title = "Distribution of Dependency Ratio by planning subzone \n(Jenks Classification)",
            main.title.position = "center",
            main.title.size = 1,
            legend.height = 0.45,
            legend.width = 0.35,
            legend.outside = FALSE,
            legend.position = c("right","bottom"),
            frame = FALSE)+
  tm_borders(alpha=0.5)
```
```{r}
tm_shape(mpsz_pop2020)+
  tm_fill("DEPENDENCY",
          style = "quantile",
          palette = "-Greens")+
  tm_borders(alpha = 0.5)+
  tmap_style("classic")
```
```{r}
tm_shape(mpsz_pop2020)+
  tm_fill("DEPENDENCY",
          style = "quantile",
          palette = "Blues",
          title = "No. of persons")+
  tm_layout(main.title = "Distribution of Dependency Ration \nby planning subzone",
            main.title.size = 1.2,
            main.title.position = "center",
            legend.height = 0.45,
            legend.width = 0.35,
            frame = TRUE)+
  tm_borders(alpha = 0.5)+
  tm_compass(type = "8star", size = 1)+
  tm_scale_bar(width = 0.15)+
  tm_grid(lwd = 0.1, alpha = 0.2)+
  tm_credits("Source: Planning Sub-zone boundary from Urban Redevelopment Authorithy (URA)\n and Population data from Department of Statistics DOS", 
             position = c("left", "bottom"))
```

```{r}
tm_style("white")
```
```{r}
tm_shape(mpsz_pop2020)+
  tm_fill(c("YOUNG","AGED"),
          style = "equal",
          palette = "Blues") +
  tm_layout(legend.position = c("right","bottom"))+
  tm_borders(alpha = 0.5)+
  tmap_style("white")
```

```{r}
tm_shape(mpsz_pop2020)+ 
  tm_polygons(c("DEPENDENCY","AGED"),
          style = c("equal", "quantile"), 
          palette = list("Blues","Greens")) +
  tm_layout(legend.position = c("right", "bottom"))
```
```{r}
tm_shape(mpsz_pop2020) +
  tm_fill("DEPENDENCY",
          style = "quantile",
          palette = "Blues",
          thres.poly = 0) + 
  tm_facets(by = "REGION_N",
            free.coords = TRUE,
            drop.shapes = TRUE)+
  tm_layout(legend.show = FALSE,
            title.position = c("center","center"),
            title.size = 20)+
  tm_borders(alpha = 0.5)
```
```{r}
youngmap = tm_shape(mpsz_pop2020)+
  tm_polygons("YOUNG",
              style = "quantile",
              palette = "Blues")
agedmap = tm_shape(mpsz_pop2020)+
  tm_polygons("AGED",
              style = "quantile",
              palette = "Blues")
tmap_arrange(youngmap,agedmap,asp = 1, ncol = 2)
```
```{r}
tm_shape(mpsz_pop2020[mpsz_pop2020$REGION_N == "CENTRAL REGION", ])+
  tm_fill("DEPENDENCY", 
          style = "quantile", 
          palette = "Blues", 
          legend.hist = TRUE, 
          legend.is.portrait = TRUE,
          legend.hist.z = 0.1) +
  tm_layout(legend.outside = TRUE,
            legend.height = 0.45, 
            legend.width = 5.0,
            legend.position = c("right", "bottom"),
            frame = FALSE) +
  tm_borders(alpha = 0.5)
```





in class ex 3:

hard coded
```{r}
percent <- c(0,.01,.1,.5,.9,.99,1)
var <- get.var("DEPENDENCY",mpszpop2020a)
bperc <- quantile(var, percent)
tm_shape(mpszpop2020) + 
  tm_polygons() +
tm_shape(mpszpop2020a) +
  tm_fill("DEPENDENCY",
          title = "DEPENDENCY",
          breaks = bperc,
          palette = "Blues",
          labels = c("< 1%", "1% - 10%", 
                     "10% - 50%", "50% - 90%",
                     "90% - 99%", "99% - 100%")) + 
  tm_borders() +
  tm_layout(title = "Percentile Map",
            title.position = c("right", "bottom"))
```

Function
```{r}
percentmap = function(vnam, df, legtitle=NA, mtitle = "Percentile Map"){
  percent <- c(0,.01,.1,.5,.9,.99,1)
  var = get.var(vnam, df)
  bperc <- quantile(var, percent)
  tm_shape(mpszpop2020) + 
    tm_polygons() +
  tm_shape(df) +
    tm_fill(vnam,
            title = legtitle,
            breaks = bperc,
            palette = "Blues",
            labels = c("< 1%", "1% - 10%", 
                       "10% - 50%", "50% - 90%",
                       "90% - 99%", "99% - 100%")) + 
    tm_borders() +
    tm_layout(title = mtitle,
              title.position = c("right", "bottom"))
}
```
```{r}
percentmap("YOUnG", mpsz2020a)
```




